ShittyFakeSpaceX/Models/ApplicationContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace ShittyFakeSpaceX.Models
{
    public class ApplicationContext : IdentityDbContext<User>
    {
        public ApplicationContext(DbContextOptions<ApplicationContext> options) : base(options)
        {
        }
    }
}

ShittyFakeSpaceX/Models/Flight.cs
using System.ComponentModel.DataAnnotations;

namespace ShittyFakeSpaceX.Models
{
    public class Flight
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Planet { get; set; }
        [Required]
        public string Station { get; set; }
        public string Terminal { get; set; }
        public string FlightNumber { get; set; }
        public string Time { get; set; }
        [Required]
        public Status Status { get; set; }


    }
    public enum Status
    {
        Arrived,
        Delayed,
        Departed,
        CheckIn,
        OnTime
    }
}

ShittyFakeSpaceX/Models/FlightContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace ShittyFakeSpaceX.Models
{
    public class FlightContext : DbContext
    {
        public DbSet<Flight> Flights { get; set; }

        public FlightContext(DbContextOptions<FlightContext> options) : base(options)
        {

        }
    }
}

ShittyFakeSpaceX/Models/User.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace ShittyFakeSpaceX.Models
{
    public class User : IdentityUser
    {
    }
}

ShittyFakeSpaceX/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ShittyFakeSpaceX.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

ShittyFakeSpaceX/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ShittyFakeSpaceX.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} at {1} character long", MinimumLength = 3)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Compare("Password", ErrorMessage = "Doesn't match")]
        [DataType(DataType.Password)]
        public string PasswordConfirm { get; set; }

        public Country Country { get; set; }
    }

    public enum Country
    {
        Canada,
        Italy,
        USA,
        Ukraine,
        Spain,
        Russia,
        Germany,
        RestOftheWorld
    }
}

ShittyFakeSpaceX/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShittyFakeSpaceX.Models;
using ShittyFakeSpaceX.ViewModels;
using System.Threading.Tasks;

namespace ShittyFakeSpaceX.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this._userManager = userManager;
            this._signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToLocal(returnUrl);

                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Wrong Login or Password");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public async Task<IActionResult> ManageUser()
        {
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }
            return View();
        }

        private Task<User> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }
    }
}

ShittyFakeSpaceX/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using ShittyFakeSpaceX.Models;

namespace ShittyFakeSpaceX.Controllers
{
    public class HomeController : Controller
    {
        private FlightContext db;
        public HomeController(FlightContext context)
        {
            this.db = context;
        }

        public IActionResult Index()
        {
            List<Flight> flights = db.Flights.ToList();
            return View(flights);
        }

        public IActionResult About()
        {

            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            return View();
        }


    }
}

ShittyFakeSpaceX/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using ShittyFakeSpaceX.Models;
using System.Collections.Generic;
using System.Linq;


namespace ShittyFakeSpaceX.Controllers
{
    public class TableController : Controller
    {
        private FlightContext db;
        public TableController(FlightContext context)
        {
            this.db = context;
        }
        public IActionResult Index()
        {
            List<Flight> flights = db.Flights.ToList();
            return View(flights);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Flights.Add(flight);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(flight);
        }
    }
}

ShittyFakeSpaceX/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="page-header">
    <div class="page-header-image" style="background-image:url(../images/start.jpg)"></div>
    <div class="container">
        <div class="col-md-4 content-center">
            <h5>This website is not realated to real SpaceX in any way. I don't own any rights for images and content. Please don't sue me.</h5>
            <h1>( ͡° ͜ʖ ͡°)</h1>
        </div>
    </div>
</div>

ShittyFakeSpaceX/Views/Home/Gallery.cshtml
<div class="wrapper">
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h4 class="title text-center">Gallery</h4>
                </div><br />
                <div class="tab-content gallery">
                    <br />
                    <div class="tab-pane active" id="home" role="tabpanel">
                        <br />
                        <div class="row">
                            <div class="col-md-10 offset-md-1">
                                <div class="row collections">
                                    <div class="col-md-4">
                                        <a href="../images/a1.jpg" target="_blank">
                                            <img src="../images/a1.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a2.jpg" target="_blank">
                                            <img src="../images/a2.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a3.jpg" target="_blank">
                                            <img src="../images/a3.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="../images/a4.jpg" target="_blank">
                                            <img src="../images/a4.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a5.jpg" target="_blank">
                                            <img src="../images/a5.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a6.jpg" target="_blank">
                                            <img src="../images/a6.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="../images/a7.jpg" target="_blank">
                                            <img src="../images/a7.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a8.jpg" target="_blank">
                                            <img src="../images/a8.jpg" alt="" class="img-thumbnail">
                                        </a>
                                        <a href="../images/a11.jpg" target="_blank">
                                            <img src="../images/a11.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="../images/a12.jpg" target="_blank">
                                            <img src="../images/a12.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="../images/a13.jpg" target="_blank">
                                            <img src="../images/a13.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="../images/a14.jpg" target="_blank">
                                            <img src="../images/a14.jpg" alt="" class="img-thumbnail">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ShittyFakeSpaceX/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShittyFake SpaceX</title>

    <environment names="Development">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/fresh-bootstrap-table.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/now-ui-kit.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body class="landing-page">
    <nav class="navbar navbar-toggleable-md bg-white fixed-top " color-on-scroll="300">
        <div class="container">
            <div class="dropdown button-dropdown">
                <a href="#" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown"></a>
            </div>
            <div class="navbar-translate">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index" rel="tooltip" title="ShittyFakeSpaceX" data-placement="bottom" style="font-size:14px">
                    ShittyFakeSpaceX
                </a>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../images/blurred-image-1.jpg">
                <ul class="navbar-nav navbar-logo navbar-switch"></ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/#Table">Flights</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/Gallery">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/#Service">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/About">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="">Have an issue?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link twitter-sharrre-nav" rel="tooltip" title="Tweet" data-placement="bottom" href="https://twitter.com/spacex" target="_blank">
                            <i class="fa fa-twitter"></i>
                            <p class="hidden-lg-up">Twitter</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link facebook-sharrre-nav" rel="tooltip" title="Share" data-placement="bottom" href="https://www.facebook.com/SpaceX/" target="_blank">
                            <i class="fa fa-facebook-square"></i>
                            <p class="hidden-lg-up">Facebook</p>
                        </a>
                    </li>
                    @await Html.PartialAsync("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>

    <div class="bootstrap-switch-container">
        @RenderBody()
        <hr />
        @*<footer>
                <p class="text-center">This site is not realated to real SpaceX in any way. I don't own any rights for images and content. Please don't sue me  ( ͡° ͜ʖ ͡°) </p>
            </footer>*@
    </div>

    <environment names="Development">
        <script src="~/js/bootstrap-switch.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/now-ui-kit.js"></script>
        <script src="~/js/tether.min.js"></script>
        <script src="~/js/bootstrap-table.js"></script>
        <script src="~/js/jquery.3.2.1.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ShittyFakeSpaceX/Views/Table/Create.cshtml
@model ShittyFakeSpaceX.Models.Flight

<form asp-action="Create" asp-controller="Table">
    <div class="form-horizontal">
        <h4> Flights</h4> <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


        <div class="form-group">
            <label asp-for="Time" class="col-md-2 control-label"></label>
            <input asp-for="Time" class="form-control" />
            <span asp-validation-for="Time" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Planet" class="col-md-2 control-label"></label>
            <input asp-for="Planet" class="form-control" />
            <span asp-validation-for="Planet" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Station" class="col-md-2 control-label"></label>
            <input asp-for="Station" class="form-control" />
            <span asp-validation-for="Station" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="FlightNumber" class="col-md-2 control-label">Flight Number</label>
            <input asp-for="FlightNumber" class="form-control" />
            <span asp-validation-for="FlightNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Terminal" class="col-md-2 control-label"></label>
            <input asp-for="Terminal" class="form-control" />
            <span asp-validation-for="Terminal" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Status" class="col-md-2 control-label"></label>
            <select asp-for="Status" asp-items="@Html.GetEnumSelectList<ShittyFakeSpaceX.Models.Status>()" class="form-control"></select>
            <span asp-validation-for="Status" class=" text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-danger col-md-2" />
        </div>

    </div>


</form>

ShittyFakeSpaceX/Views/Table/Index.cshtml
@model IEnumerable<ShittyFakeSpaceX.Models.Flight>

@{
    ViewData["Title"] = "Flights";
}

<h2>Flights overview</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>


<div class="section">
    <div class="container-fluid">
        <div class="row">
            <div class=" col-md-8 offset-md-2 text-center">
                <div class="title text-center"><h2>Flights Schedule</h2></div>
                <div class="fresh-table fixed-table-body table-hover full-color-azure">
                    <table class="table">
                        <thead class="text-uppercase"><tr><td><h6>Time</h6></td><td><h6>Planet</h6></td><td><h6>Station</h6></td><td><h6>Flight Number</h6></td><td><h6>Terminal</h6></td><td><h6>Status</h6></td></tr></thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr><td>@item.Time</td><td>@item.Planet</td><td>@item.Station</td><td>@item.FlightNumber</td><td>@item.Terminal</td><td>@item.Status</td></tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>